module.exports = {

    ResponseCode : {
      DEFAULT: 0,
      OK: 1,
      ERROR: 2,
      SESSIONEXPIRED: 3,
      AUTHFAILED: 4,
      SUSPENDED: 12,
      INVALIDCLIENTVERSION: 50,
      FORCECLIENTRESTART: 51
    },

    AllyStatus : {
      ALLIED: 0,
      REQUESTSENT: 1
    },

    BindOption : {
      BIND: 0,
      DONTBIND: 1,
      BINDOPTIONNULL: 2
    },

    SessionStartContext : {
      PUSHNOTE: 0,
      NORMALAPPSTART: 1,
      RESUME: 2,
      RESTART: 3
    },

    AuthServiceType : {
      UNKNOWNAUTH: 0,
      GUESTAUTH: 1,
      GOOGLEPLAYAUTH: 2,
      GAMECENTERAUTH: 3,
      GOOGLEGAMESAUTH: 4
    },

    CampaignType : {
      NOCAMPAIGNTYPE: 0,
      STANDARD: 1,
      ONBOARDING: 2,
      CAMPAIGNEVENT: 3,
      GUILDRAID: 4,
      CAMPAIGNPVELIGHT: 5,
      CAMPAIGNPVEDARK: 6,
      CAMPAIGNPVEMODBATTLES: 7,
      CAMPAIGNPVEHOLOCRON: 8,
      CAMPAIGNSHIPPVE: 9,
      TERRITORYBATTLE: 11
    },

    MoveType : {
      NOMOVETYPE: 0,
      MOVETYPEATTACK: 1,
      MOVETYPELIMITBREAK: 2,
      MOVETYPECRYSTAL: 3,
      MOVETYPENONE: 4,
      MOVETYPELEADERABILITY: 5,
      MOVETYPECONSUMABLE: 6
    },

    BattleLootReason : {
      NOBATTLELOOTREASON: 0,
      ONHIT: 1,
      ONDEATH: 2,
      COMPLETEREWARD: 3
    },

    BattleTurnOwner : {
      NOBATTLETURNOWNER: 0,
      PLAYER: 1,
      OPPONENT: 2
    },

    BattleRecordType : {
      NOBATTLERECORDTYPE: 0,
      BATTLERECORDABILITY: 1,
      BATTLERECORDCONDITION: 2,
      BATTLERECORDDAMAGE: 3,
      BATTLERECORDEFFECTAPPLIED: 4,
      BATTLERECORDEFFECTEXPIRED: 5,
      BATTLERECORDEFFECT: 6,
      BATTLERECORDPLAYERAUTOTOGGLE: 7,
      BATTLERECORDPLAYERMANUALABILITY: 8,
      BATTLERECORDPLAYERMANUALSELECT: 9,
      BATTLERECORDRECOVERY: 10,
      BATTLERECORDENCOUNTERSTART: 11,
      BATTLERECORDENCOUNTEREND: 12,
      BATTLERECORDOPENINGMOVE: 13,
      BATTLERECORDSELECTREINFORCEMENT: 14,
      BATTLERECORDDESTROY: 15
    },

    BattleType : {
      NOBATTLETYPE: 0,
      PVEBATTLE: 1,
      PVPBATTLE: 2,
      WARBATTLE: 3,
      GUILDRAIDBATTLE: 4,
      TERRITORYSTRIKEBATTLE: 5,
      TERRITORYCOVERTBATTLE: 6,
      TERRITORYWARBATTLE: 7
    },

    BattleOutcome : {
      NOBATTLEOUTCOME: 0,
      WIN: 1,
      LOSS: 2,
      RETREAT: 3,
      DRAW: 4
    },

    WarNodeStatus : {
      NOWARNODESTATUS: 0,
      NODEHIDDEN: 1,
      NODELOCKED: 2,
      NODEUNLOCKED: 3,
      NODECLAIMABLE: 4,
      NODECOMPLETED: 5
    },

    ChannelEventType : {
      DEFAULT: 0,
      CHATMESSAGE: 1,
      ACTIVITYEVENT: 2
    },

    PlayerReportType : {
      NOPLAYERREPORTTYPE: 0,
      OFFENSIVELANGUAGE: 1,
      OFFENSIVENAME: 2,
      CHEATING: 3
    },

    ChatInboxWhitelistCategory : {
      NOCHATINBOXWHITELISTCATEGORY: 0,
      EVERYONE: 1,
      ALLIES: 2,
      GUILD: 3,
      NOBODY: 4
    },

    RpcHttpRequestMethod : {
      NORPCHTTPREQUESTMETHOD: 0,
      HTTPPOST: 1,
      HTTPGET: 2
    },

    PerformanceLevel : {
      NOPERFORMANCELEVEL: 0,
      PERFORMANCELOW: 1,
      PERFORMANCEMEDIUM: 2,
      PERFORMANCEHIGH: 3
    },

    MemoryLevel : {
      NOMEMORYLEVEL: 0,
      MEMORYLOW: 1,
      MEMORYMEDIUM: 2,
      MEMORYHIGH: 3
    },

    GcActivityLevel : {
      NOGCACTIVITYLEVEL: 0,
      GCACTIVITYLOW: 1,
      GCACTIVITYMEDIUM: 2,
      GCACTIVITYHIGH: 3
    },

    VfxAllocationLevel : {
      NOVFXALLOCATIONLEVEL: 0,
      VFXONDEMAND: 1,
      VFXPRELOAD: 2,
      VFXPRELOADANDALLOCATE: 3
    },

    ClientCacheDomain : {
      NOCLIENTCACHEDOMAIN: 0,
      ASSETS: 1,
      GAMEDATA: 2,
      PLAYERPREFS: 3,
      LOCALIZATION: 4
    },

    AbilityButtonLocationType : {
      NOABILITYBUTTONLOCATIONTYPE: 0,
      ABILITYSTANDARD: 1,
      ABILITYADDITIONAL: 2,
      ABILITYHIDDEN: 3,
      ABILITYSECONDSTANDARD: 4
    },

    UnitDetailsAbilityLocation : {
      NOUNITDETAILSABILITYLOCATION: 0,
      ABILITYLOCATIONNORMAL: 1,
      ABILITYLOCATIONADVANCED: 2,
      ABILITYLOCATIONCREW: 3,
      ABILITYLOCATIONHIDDEN: 4
    },

    ColorType : {
      NOCOLORTYPE: 0,
      WHITE: 1,
      RED: 2,
      ORANGE: 3,
      YELLOW: 4,
      GREEN: 5,
      BLUE: 6
    },

    ItemType : {
      NOITEMTYPE: 0,
      EMPTY: 1,
      UNIT: 2,
      CURRENCY: 3,
      BUCKET: 4,
      CONSUMABLE: 5,
      XP: 6,
      MATERIAL: 7,
      ENERGY: 8,
      UNITSHARD: 9,
      RECIPE: 10,
      EQUIPMENT: 11,
      EVENTKEYCARD: 12,
      POWERUPBUNDLE: 13,
      MYSTERYBOX: 14,
      STATMOD: 15,
      MYSTERYSTATMOD: 16,
      PLAYERTITLE: 17
    },

    Rarity : {
      NORARITY: 0,
      ONESTAR: 1,
      TWOSTAR: 2,
      THREESTAR: 3,
      FOURSTAR: 4,
      FIVESTAR: 5,
      SIXSTAR: 6,
      SEVENSTAR: 7,
      NOSTAR: 8
    },

    CurrencyType : {
      NOCURRENCYTYPE: 0,
      GRIND: 1,
      PREMIUM: 2,
      REALMONEY: 3,
      SOCIAL: 4,
      IGCEVENTKEYCARD: 8,
      XPEVENTKEYCARD: 9,
      PVPCURRENCY: 10,
      FORCEPOINT: 11,
      PVPSHIPCURRENCY: 12,
      FREE: 13,
      WARSHIPCURRENCY: 14,
      GRINDTICKET: 15,
      SHARDCURRENCY: 16,
      GUILDCURRENCY: 17,
      GUILDBANKCURRENCY: 18,
      SHIPGRIND: 19,
      GUILDRAIDCURRENCY01: 20,
      GUILDRAIDCURRENCY02: 21,
      GUILDRAIDCURRENCY03: 22,
      GUILDRAIDCURRENCY04: 23,
      GUILDRAIDCURRENCY05: 24,
      GUILDRAIDCURRENCY06: 25,
      GUILDRAIDCURRENCY07: 26,
      GUILDRAIDCURRENCY08: 27,
      GUILDRAIDCURRENCY09: 28,
      GUILDRAIDCURRENCY10: 29,
      GUILDRAIDCURRENCY11: 30,
      GUILDRAIDCURRENCY12: 31,
      TERRITORYBATTLECURRENCY: 32
    },

    ThreatLevel : {
      NOTHREATLEVEL: 0,
      NORMAL: 1,
      ELITE: 2,
      BOSS: 3,
      ANY: 4
    },

    ContextualMessageType : {
      NOCONTEXTUALMESSAGETYPE: 0,
      POINTATVIEWELEMENT: 1,
      CHARACTERDIALOG: 3,
      MODALDIALOGONEBUTTON: 4,
      MODALDIALOGTWOBUTTON: 5,
      CANTINACHARACTERDIALOG: 6,
      UNITUNLOCK: 7,
      STOREPROMODIALOG: 8,
      CHALLENGEQUESTREWARDS: 9
    },

    SquadType : {
      NOSQUADTYPE: 0,
      SQUADNEUTRAL: 1,
      SQUADLIGHT: 2,
      SQUADDARK: 3,
      SQUADEVENT: 4,
      SQUADPVP: 5,
      SQUADRESTRICTED: 6,
      SQUADSUPPLIED: 7,
      SQUADWAR: 8,
      SQUADEVENT01: 9,
      SQUADEVENT02: 10,
      SQUADEVENT03: 11,
      SQUADEVENT04: 12,
      SQUADEVENT05: 13,
      SQUADEVENT06: 14,
      SQUADEVENT07: 15,
      SQUADEVENT08: 16,
      SQUADEVENT09: 17,
      SQUADEVENT10: 18,
      SQUADEVENT11: 19,
      SQUADEVENT12: 20,
      SQUADEVENT13: 21,
      SQUADEVENT14: 22,
      SQUADEVENT15: 23,
      SQUADEVENT16: 24,
      SQUADEVENT17: 25,
      SQUADEVENT18: 26,
      SQUADEVENT19: 27,
      SQUADEVENT20: 28,
      SQUADWARDEFENSIVE: 29,
      SQUADGUILDRAID: 30,
      SQUADSTATMODBATTLES: 31,
      SQUADEVENTDEFENSIVE: 32,
      SQUADEVENTDEFENSIVE01: 33,
      SQUADEVENTDEFENSIVE02: 34,
      SQUADEVENTDEFENSIVE03: 35,
      SQUADEVENTDEFENSIVE04: 36,
      SQUADEVENTDEFENSIVE05: 37,
      SQUADEVENTDEFENSIVE06: 38,
      SQUADEVENTDEFENSIVE07: 39,
      SQUADEVENTDEFENSIVE08: 40,
      SQUADEVENTDEFENSIVE09: 41,
      SQUADEVENTDEFENSIVE10: 42,
      SQUADEVENTDEFENSIVE11: 43,
      SQUADEVENTDEFENSIVE12: 44,
      SQUADEVENTDEFENSIVE13: 45,
      SQUADEVENTDEFENSIVE14: 46,
      SQUADEVENTDEFENSIVE15: 47,
      SQUADEVENTDEFENSIVE16: 48,
      SQUADEVENTDEFENSIVE17: 49,
      SQUADEVENTDEFENSIVE18: 50,
      SQUADEVENTDEFENSIVE19: 51,
      SQUADEVENTDEFENSIVE20: 52,
      SQUADTERRITORYWARATTACK: 53,
      SQUADTERRITORYWARDEFENSIVE: 54
    },

    InterstitialMessageType : {
      NOINTERSTITIALMESSAGETYPE: 0,
      TICKER: 1,
      NEWSLETTER: 2,
      HOMEPROMO: 3
    },

    InterstitialTriggerType : {
      NOINTERSTITIALTRIGGERTYPE: 0,
      EVENT: 1,
      CHALLENGE: 2,
      STORE: 3
    },

    NewsletterMessageType : {
      NONEWSLETTERMESSAGETYPE: 0,
      TEXT: 1,
      TEXTWITHTEXTURE: 2
    },

    TickerAppearLocation : {
      NOTICKERAPPEARLOCATION: 0,
      HOMEBASETICKER: 1,
      STORETICKER: 2
    },

    InboxMessageType : {
      NOINBOXMESSAGETYPE: 0,
      BASIC: 1,
      ALLYREQUEST: 2,
      STORERECEIPT: 3,
      RANKREWARD: 4,
      GUILDINVITE: 5,
      JOINGUILDREQUEST: 6,
      GUILDRANKEDREWARD: 7,
      GUILDEXCHANGEAWARD: 8,
      GAMEEVENTREWARD: 9,
      TERRITORYBATTLECOMPLETEREWARD: 10,
      TERRITORYCOVERTMISSIONREWARD: 11,
      TERRITORYWARCOMPLETEREWARD: 12,
      CHATROOMINVITATION: 13
    },

    UnitClass : {
      NOUNITCLASS: 0,
      UNITCLASSSTANDARD: 6,
      UNITCLASSCOMMANDER: 7
    },

    CombatType : {
      NOCOMBATTYPE: 0,
      CHARACTER: 1,
      SHIP: 2
    },

    ForceAlignment : {
      NOFORCEALIGNMENT: 0,
      NEUTRAL: 1,
      LIGHT: 2,
      DARK: 3
    },

    ConditionType : {
      NOCONDITIONTYPE: 0,
      ROUNDCOUNT: 1,
      ENDOFROUND: 2,
      STARTOFROUND: 3,
      STARTOFBATTLE: 4,
      CHANCE: 5,
      STARTOFENCOUNTER: 7,
      CRIT: 8,
      RECEIVECRIT: 9,
      PERFORMMOVE: 10,
      ATTACK: 11,
      LIMITBREAK: 12,
      RECEIVEDAMAGE: 13,
      RECEIVEHEAL: 14,
      COMBO: 15,
      RECEIVECOMBO: 16,
      KILL: 17,
      REVIVE: 18,
      ENEMYKILLED: 19,
      ALLYKILLED: 20,
      DEATH: 21,
      ALLYREVIVED: 22,
      ENEMYREVIVED: 23,
      ENDOFENCOUNTER: 24,
      STARTOFTURN: 25,
      HEALTHDECREASE: 26,
      HEALTHINCREASE: 27,
      PERSISTENTEFFECTADD: 28,
      PERSISTENTEFFECTREMOVE: 29,
      DODGED: 30,
      WASDODGED: 31,
      ENDOFTURN: 32,
      RESISTED: 33,
      WASRESISTED: 34,
      STARTMOVE: 35,
      STARTATTACK: 36,
      STARTLIMITBREAK: 37,
      PREEFFECTEVAL: 38,
      RECEIVEPREEFFECTEVAL: 39,
      POSTEFFECTEVAL: 40,
      RECEIVEPOSTEFFECTEVAL: 41,
      PREEVASIONEVAL: 42,
      RECEIVEPREEVASIONEVAL: 43,
      POSTEVASIONEVAL: 44,
      RECEIVEPOSTEVASIONEVAL: 45,
      STARTOFGUILDRAIDFORPLAYER: 46,
      STARTOFGUILDRAIDENCOUNTERFORPLAYER: 47,
      PRERECEIVEDAMAGE: 48,
      FULLTURNCOMPLETE: 49,
      PERSISTENTEFFECTADDINSTANCE: 50,
      PERSISTENTEFFECTREMOVEINSTANCE: 51,
      FLED: 52,
      ALLYFLED: 53,
      ENEMYFLED: 54,
      REINFORCED: 55,
      ALLYREINFORCED: 56,
      ENEMYREINFORCED: 57,
      DEALDAMAGE: 58,
      PERSISTENTEFFECTINFLICTED: 59,
      PERSISTENTEFFECTINFLICTEDINSTANCE: 60,
      DODGEDPOSTEVASIONEVAL: 61,
      HEALTHMAXLIMITREACHED: 62,
      HEALTHMINLIMITREACHED: 63
    },

    AbilityType : {
      NOABILITYTYPE: 0,
      ABILITYACTIVATED: 7,
      ABILITYPASSIVE: 8,
      ABILITYREINFORCEMENT: 9,
      ABILITYACTIVATEDALLYSELECT: 10
    },

    EffectType : {
      NOEFFECTTYPE: 0,
      DAMAGE: 1,
      RECOVER: 2,
      PARALYSIS: 3,
      CURSE: 4,
      DISPELL: 5,
      IMMUNITY: 6,
      BONUSMOVE: 7,
      MODIFYSTAT: 8,
      APPLYEFFECT: 9,
      DISTRIBUTERECOVERY: 10,
      QUERYCOUNT: 11,
      QUERYSTAT: 12,
      REVIVEUNIT: 13,
      SCRIPTCOMPONENT: 14,
      FLEE: 15,
      DESTROY: 16,
      REINFORCE: 17,
      GRANTSHIELD: 18,
      GRANTABILITY: 19,
      HEALTHLIMIT: 20
    },

    EffectApplyType : {
      NOEFFECTAPPLYTYPE: 0,
      UNAVOIDABLE: 1,
      PHYSICAL: 2,
      MENTAL: 3
    },

    EffectDamageType : {
      NOEFFECTDAMAGETYPE: 0,
      UNMITIGABLE: 1,
      ATTACKDAMAGE: 2,
      ABILITYPOWER: 3
    },

    ChanceRollType : {
      NOCHANCEROLLTYPE: 0,
      PERUNIT: 1,
      ALLTARGETS: 2
    },

    EffectTargetUnitSelect : {
      NOEFFECTTARGETUNITSELECT: 0,
      SELECTALL: 1,
      SELECTEDTARGET: 2,
      SELECTRANDOM: 3,
      SELECTSELF: 4,
      SELECTPREVIOUS: 5,
      SELECTLASTREINFORCEMENT: 6,
      SELECTLOWESTSURVIVABILITY: 7,
      SELECTHIGHESTSURVIVABILITY: 8,
      SELECTLEADER: 9,
      SELECTSUPPORT: 10
    },

    EffectTargetBattleSide : {
      NOEFFECTTARGETBATTLESIDE: 0,
      BOTHSIDES: 1,
      ALLYSIDE: 2,
      ENEMYSIDE: 3,
      PLAYERSIDE: 4,
      OPPONENTSIDE: 5
    },

    UnitHealthState : {
      NOUNITHEALTHSTATE: 0,
      UNITHEALTHSTATEANY: 1,
      UNITHEALTHSTATEALIVE: 2,
      UNITHEALTHSTATEDEAD: 3
    },

    BattleDeploymentState : {
      NOBATTLEDEPLOYMENTSTATE: 0,
      BATTLEDEPLOYMENTSTATEANY: 1,
      BATTLEDEPLOYMENTSTATEDEPLOYED: 2,
      BATTLEDEPLOYMENTSTATEREINFORCEMENT: 3
    },

    RequirementType : {
      NOREQUIREMENTTYPE: 0,
      CURRENCYREQUIREMENT: 3,
      ROSTERCHARACTERNOTCATEGORYNOTINSQUADREQUIREMENT: 10,
      SQUADSIZEMAXIMUMREQUIREMENT: 11,
      ROSTERCHARACTERCATEGORYNOTINUSEREQUIREMENT: 12,
      ROSTERCHARACTERNOTINUSEREQUIREMENT: 13,
      SQUADSIZEMINIMUMREQUIREMENT: 14,
      ENEMYTHREATLEVELREQUIREMENT: 15,
      ANYCHARACTERREADYFORPROMOTION: 16,
      UNITTRAININGAVAILABLE: 19,
      PLAYERLEVELMINREQUIREMENT: 20,
      ROSTERUNITTYPEREQUIREMENT: 22,
      ROSTERUNITTYPEMAXREQUIREMENT: 23,
      UNITABILITYUPGRADEAVAILABLE: 24,
      UNITGEAREQUIPAVAILABLE: 25,
      CURRENTUNITGEAREQUIPAVAILABLE: 26,
      PLAYERUNITHEALTHBELOWPERCENT: 27,
      REQUIREMENTINVALID: 28,
      CURRENTCHARACTERREADYFORPROMOTION: 29,
      BATTLEANYSTATUSEFFECTACTIVE: 30,
      STOREITEMAVAILABLEFORPURCHASE: 31,
      CURRENTMISSIONHASGEARDROP: 32,
      PLAYERLEVELMAXREQUIREMENT: 33,
      CAMPAIGNREQUIREMENT: 34,
      ANYDAILYACTIVITYREADYFORCLAIM: 35,
      FACEBOOKLOGINAVAILABLE: 36,
      ANYUNITREACHEDMAXRARITY: 37,
      CURRENTCHARACTERREADYFORTIERUP: 38,
      EVENTACTIVE: 39,
      BATTLEANYUNITHASSHIELD: 40,
      CURRENTCHARACTERMINTIER: 41,
      UNITLEVELMAXREQUIREMENT: 42,
      UNITLEVELMINREQUIREMENT: 43,
      ROSTERUNITREQUIREMENT: 44,
      UNITSHARDREQUIREMENT: 45,
      ROSTERUNITCOMBATTYPEREQUIREMENT: 46,
      BATTLETURNCOUNT: 47,
      BATTLEENCOUNTERSTARTED: 48,
      BATTLEUNITTURNSQUADCELLINDEX: 49,
      ROSTERUNITCLASSREQUIREMENT: 50,
      SHIPSUNLOCKED: 51,
      UNITHASALLYABILITYREQUIREMENT: 52,
      UNITHASREINFORCEMENTABILITYREADY: 53,
      REINFORCEMENTSLOTAVAILABLE: 54,
      ROSTERCANBUILDVALIDSQUADREQUIREMENT: 55,
      BATTLEACTIVECOMBATTYPE: 56,
      BATTLEPLAYERUNITABILITYCANBEACTIVATED: 57,
      BATTLETURNOWNER: 58,
      ROSTERUNITNOTOWNEDREQUIREMENT: 59,
      UNITUNLOCKREQUIREMENT: 60,
      GUILDTERRITORYMAPCONFLICTCOMPLETED: 61,
      GUILDTERRITORYRECONSCOREMIN: 62,
      GUILDTERRITORYRECONSCOREMAX: 63,
      UNITDEPLOYREQUIREMENT: 64,
      GUILDTERRITORYZONESTATUS: 65,
      TERRITORYWAREVENTAVAILABLE: 66,
      CHALLENGEQUESTREWARDSPENDING: 67,
      QUESTCOMPLETEREQUIREMENT: 68
    },

    EvaluationType : {
      NOEVALUATIONTYPE: 0,
      AND: 1,
      OR: 2
    },

    DynamicDescriptionType : {
      NODYNAMICDESCRIPTIONTYPE: 0,
      LAYOUTTEXT: 1,
      LAYOUTUNIT: 2,
      LAYOUTABILITY: 3,
      LAYOUTHEADER: 4,
      LAYOUTTEXTCOLUMN: 5,
      LAYOUTHORIZONTALBREAK: 6
    },

    DynamicDescriptionTextAlignmentType : {
      NODYNAMICDESCRIPTIONTEXTALIGNMENTTYPE: 0,
      TEXTALIGNMENTLEFT: 1,
      TEXTALIGNMENTRIGHT: 2,
      TEXTALIGNMENTCENTER: 3
    },

    DynamicMessageType : {
      NODYNAMICMESSAGETYPE: 0,
      CONTEXTUALMESSAGE: 1,
      CAMPAIGNSTATUSUPDATE: 2,
      STOREUPDATE: 3,
      INBOXUPDATE: 4,
      GAMEEVENTUPDATE: 5,
      CHALLENGEUPDATE: 7,
      SUSPENSIONDETAILS: 8,
      DAILYACTIONCAPSTATUS: 9,
      COOLDOWNSTATUS: 10,
      PLAYERUPDATE: 11
    },

    BattleUnitStateStat : {
      NOBATTLEUNITSTATESTAT: 0,
      BATTLEUNITSTATUNDEFINED: 1,
      BATTLEUNITSTATHEALTH: 2,
      BATTLEUNITSTATHEALTHPERCENT: 3,
      BATTLEUNITSTATSPEEDFILL: 4,
      BATTLEUNITSTATSPEEDFILLPERCENT: 5,
      BATTLEUNITSTATSHIELDPERCENT: 6
    },

    AbilityCooldownType : {
      NOABILITYCOOLDOWNTYPE: 0,
      ABILITYCOOLDOWNTURNBASED: 1,
      ABILITYCOOLDOWNSPEEDBASED: 2
    },

    UnitTier : {
      NOUNITTIER: 0,
      TIER01: 1,
      TIER02: 2,
      TIER03: 3,
      TIER04: 4,
      TIER05: 5,
      TIER06: 6,
      TIER07: 7,
      TIER08: 8,
      TIER09: 9,
      TIER10: 10,
      TIER11: 11,
      TIER12: 12,
      TIER13: 13,
      TIER14: 14,
      TIER15: 15,
      TIER16: 16,
      TIER17: 17,
      TIER18: 18,
      TIER19: 19,
      TIER20: 20
    },

    UnitStat : {
      NOUNITSTAT: 0,
      UNITSTATMAXHEALTH: 1,
      UNITSTATSTRENGTH: 2,
      UNITSTATAGILITY: 3,
      UNITSTATINTELLIGENCE: 4,
      UNITSTATSPEED: 5,
      UNITSTATATTACKDAMAGE: 6,
      UNITSTATABILITYPOWER: 7,
      UNITSTATARMOR: 8,
      UNITSTATSUPPRESSION: 9,
      UNITSTATARMORPENETRATION: 10,
      UNITSTATSUPPRESSIONPENETRATION: 11,
      UNITSTATDODGERATING: 12,
      UNITSTATDEFLECTIONRATING: 13,
      UNITSTATATTACKCRITICALRATING: 14,
      UNITSTATABILITYCRITICALRATING: 15,
      UNITSTATCRITICALDAMAGE: 16,
      UNITSTATACCURACY: 17,
      UNITSTATRESISTANCE: 18,
      UNITSTATDODGEPERCENTADDITIVE: 19,
      UNITSTATDEFLECTIONPERCENTADDITIVE: 20,
      UNITSTATATTACKCRITICALPERCENTADDITIVE: 21,
      UNITSTATABILITYCRITICALPERCENTADDITIVE: 22,
      UNITSTATARMORPERCENTADDITIVE: 23,
      UNITSTATSUPPRESSIONPERCENTADDITIVE: 24,
      UNITSTATARMORPENETRATIONPERCENTADDITIVE: 25,
      UNITSTATSUPPRESSIONPENETRATIONPERCENTADDITIVE: 26,
      UNITSTATHEALTHSTEAL: 27,
      UNITSTATMAXSHIELD: 28,
      UNITSTATSHIELDPENETRATION: 29,
      UNITSTATHEALTHREGEN: 30,
      UNITSTATATTACKDAMAGEPERCENTADDITIVE: 31,
      UNITSTATABILITYPOWERPERCENTADDITIVE: 32,
      UNITSTATDODGENEGATEPERCENTADDITIVE: 33,
      UNITSTATDEFLECTIONNEGATEPERCENTADDITIVE: 34,
      UNITSTATATTACKCRITICALNEGATEPERCENTADDITIVE: 35,
      UNITSTATABILITYCRITICALNEGATEPERCENTADDITIVE: 36,
      UNITSTATDODGENEGATERATING: 37,
      UNITSTATDEFLECTIONNEGATERATING: 38,
      UNITSTATATTACKCRITICALNEGATERATING: 39,
      UNITSTATABILITYCRITICALNEGATERATING: 40,
      UNITSTATOFFENSE: 41,
      UNITSTATDEFENSE: 42,
      UNITSTATDEFENSEPENETRATION: 43,
      UNITSTATEVASIONRATING: 44,
      UNITSTATCRITICALRATING: 45,
      UNITSTATEVASIONNEGATERATING: 46,
      UNITSTATCRITICALNEGATERATING: 47,
      UNITSTATOFFENSEPERCENTADDITIVE: 48,
      UNITSTATDEFENSEPERCENTADDITIVE: 49,
      UNITSTATDEFENSEPENETRATIONPERCENTADDITIVE: 50,
      UNITSTATEVASIONPERCENTADDITIVE: 51,
      UNITSTATEVASIONNEGATEPERCENTADDITIVE: 52,
      UNITSTATCRITICALCHANCEPERCENTADDITIVE: 53,
      UNITSTATCRITICALNEGATECHANCEPERCENTADDITIVE: 54,
      UNITSTATMAXHEALTHPERCENTADDITIVE: 55,
      UNITSTATMAXSHIELDPERCENTADDITIVE: 56,
      UNITSTATSPEEDPERCENTADDITIVE: 57,
      UNITSTATCOUNTERATTACKRATING: 58,
      UNITSTATTAUNT: 59
    },

    SkillType : {
      NOSKILLTYPE: 0,
      UNITSKILL: 1,
      CREWSKILL: 2
    },

    UnitType : {
      NOUNITTYPE: 0,
      UNITTYPESTANDARD: 1,
      UNITTYPEXP: 2,
      UNITTYPESELL: 3,
      UNITTYPEPROMOTE: 4
    },

    ConsumableCriteriaHealthState : {
      NOCONSUMABLECRITERIAHEALTHSTATE: 0,
      ALIVE: 1,
      DEAD: 2,
      DAMAGED: 3
    },

    ConsumableCriteriaLimitBreakState : {
      NOCONSUMABLECRITERIALIMITBREAKSTATE: 0,
      FULL: 1,
      NOTFULL: 2,
      CRITERIANONE: 3
    },

    CampaignElementProgress : {
      NOCAMPAIGNELEMENTPROGRESS: 0,
      HIDDEN: 1,
      LOCKED: 2,
      UNLOCKED: 3,
      COMPLETEONESTAR: 5,
      COMPLETETWOSTAR: 6,
      COMPLETETHREESTAR: 7
    },

    CampaignNodeDifficulty : {
      NOTSET: 0,
      NORMALDIFF: 4,
      HARDDIFF: 5,
      NIGHTMAREDIFF: 6,
      SPECIALDIFF: 7,
      IDIFF: 8,
      IIDIFF: 9,
      IIIDIFF: 10,
      IVDIFF: 11,
      VDIFF: 12,
      VIDIFF: 13
    },

    CategoryMatchType : {
      NOCATEGORYMATCHTYPE: 0,
      MATCHALL: 1,
      MATCHANY: 2
    },

    OperationType : {
      NOOPERATIONTYPE: 0,
      ADDITIVE: 1,
      MULTIPLICATIVE: 2
    },

    InventoryDeltaReason : {
      NOINVENTORYDELTAREASON: 0,
      SILENT: 1,
      CHEAT: 2,
      BATTLESTART: 3,
      BATTLEFINISH: 4,
      PLAYERLEVELUPBONUS: 5,
      ALLYGIFTAWARD: 7,
      ALLYINCENTIVEAWARD: 8,
      STOREPURCHASE: 9,
      CRAFTITEMS: 10,
      TRAINUNIT: 11,
      PROMOTEUNIT: 12,
      PAYTOCONTINUE: 13,
      SELLITEMS: 14,
      INBOXMESSAGE: 15,
      SCOREBONUS: 16,
      ENTERKEYCARDEVENT: 17,
      DAILYLOGINAWARD: 18,
      CHALLENGEAWARD: 19,
      ITEMCONVERSION: 20,
      SHIPMENTREFRESH: 21,
      ENERGYREFRESH: 22,
      ENABLEDPUSHNOTES: 23,
      BATTLESTARTPVP: 24,
      BATTLEFINISHPVP: 25,
      DAILYREWARDPVP: 26,
      NEWRANKPVP: 27,
      SHIPMENTSPVP: 28,
      SHIPMENTSPVE: 30,
      BATTLESTARTPVPSHIP: 31,
      BATTLEFINISHPVPSHIP: 32,
      SKILLUPGRADE: 33,
      REFRESHCOOLDOWN: 34,
      RESETDAILYACTIONCAP: 35,
      EQUIPGEAR: 36,
      GEARTIERINCREASE: 37,
      SHIPMENTSSHIPWAR: 38,
      SHIPMENTSCANTINA: 39,
      WARCHEST: 40,
      SHIPMENTSSHIPPVP: 41,
      FACEBOOKCONNECT: 42,
      REDEMPTIONCODE: 44,
      SHIPMENTSSHARD: 45,
      GUILDCREATE: 46,
      SHIPMENTSGUILD: 47,
      GUILDRANKEDREWARDS: 48,
      GUILDSUPPORT: 49,
      RAIDREWARD: 50,
      RAIDACTIVATE: 51,
      SHIPMENTSMOD: 52,
      DONATIONSEND: 53,
      DONATIONRECEIVE: 54,
      DONATIONREWARD: 55,
      SHIPMENTSTERRITORY: 56
    },

    EnergyType : {
      NOENERGYTYPE: 0,
      PVE: 1,
      PVP: 2,
      SHIPPVE: 3,
      SHIPPVP: 4,
      CANTINAPVE: 5
    },

    GameFeature : {
      NOGAMEFEATURE: 0,
      PLAYERRENAME: 1
    },

    RoomType : {
      NOROOMTYPE: 0,
      GUILDDEFAULT: 1,
      GUILDCHAT: 2,
      GUILDCHATOFFICER: 3,
      PLAYERDIRECTCHAT: 4,
      PLAYERGROUPCHAT: 5
    },

    PointAtRotationBehavior : {
      NOPOINTATROTATIONBEHAVIOR: 0,
      ROTATIONBEHAVIORNONE: 1,
      ROTATIONBEHAVIORAUTOFROMCENTER: 2,
      ROTATIONBEHAVIORAUTOFROMCENTERIFCLAMPED: 3
    },

    PointerType : {
      NOPOINTERTYPE: 0,
      POINT: 1,
      CLICK: 2,
      SWIPE: 3
    },

    GameEventType : {
      NOGAMEEVENTTYPE: 0,
      SCHEDULED: 1,
      KEYCARD: 2,
      PROGRESSION: 3,
      MODS: 4,
      PVPEVENT: 5,
      ECONOMYEVENT: 6,
      TERRITORYMAPEVENT: 7,
      TERRITORYWAREVENT: 8,
      TERRITORYBATTLEEVENT: 9
    },

    GameEventStatus : {
      NOGAMEEVENTSTATUS: 0,
      EVENTLOCKED: 1,
      EVENTUNLOCKED: 2
    },

    GameEventUILocation : {
      NOGAMEEVENTUILOCATION: 0,
      GAMEEVENTUILOCATIONTRIALS: 1,
      GAMEEVENTUILOCATIONEVENTS: 2,
      GAMEEVENTUILOCATIONMODS: 3,
      GAMEEVENTUILOCATIONSHIPTRIALS: 4,
      GAMEEVENTUILOCATIONNONE: 5
    },

    RecipeType : {
      NORECIPETYPE: 0,
      RECIPEINVALID: 1,
      RECIPEPROMOTION: 2,
      RECIPESHIP: 3,
      RECIPECONSUMABLE: 4,
      RECIPECHARACTER: 5,
      RECIPESKILL: 6,
      RECIPEEQUIPMENT: 7
    },

    MaterialType : {
      NOMATERIALTYPE: 0,
      CRAFTINGMATERIAL: 1,
      XPMATERIAL: 2,
      UNITSHARDMATERIAL: 3,
      PROMOTIONMATERIAL: 4,
      SKILLMATERIAL: 5,
      SELLMATERIAL: 6,
      SHIPXPMATERIAL: 7,
      SHIPSKILLMATERIAL: 8
    },

    EquipmentType : {
      NOEQUIPMENTTYPE: 0,
      EQUIPMENTEQUIPPABLE: 1,
      EQUIPMENTUNRELEASED: 2,
      EQUIPMENTMATERIAL: 3
    },

    HelpType : {
      NOHELPTYPE: 0,
      BATTLE: 1,
      SQUAD: 2,
      PROGRESS: 3
    },

    ModifierLocationType : {
      NOMODIFIERLOCATIONTYPE: 0,
      MODIFIERLOCATIONCAMPAIGN: 1,
      MODIFIERLOCATIONGALACTICWAR: 2
    },

    ChallengeType : {
      NOCHALLENGETYPE: 0,
      DAILYCHALLENGE: 1,
      LIFETIMECHALLENGE: 2,
      QUESTCHALLENGE: 3,
      PLAYERACTIVATEDCHALLENGE: 4
    },

    ChallengeRewardType : {
      NOCHALLENGEREWARDTYPE: 0,
      CHALLENGEREWARDFIXED: 1,
      CHALLENGEREWARDRATIO: 2
    },

    ChallengeClaimType : {
      NOCHALLENGECLAIMTYPE: 0,
      CHALLENGECLAIMMANUAL: 1,
      CHALLENGECLAIMAUTOMATIC: 2
    },

    WarNodeType : {
      NOWARNODETYPE: 0,
      NODETYPEOPPONENT: 1,
      NODETYPECHESTCOMMON: 2,
      NODETYPECHESTRARE: 3,
      NODETYPECHESTEPIC: 4
    },

    ActionLinkType : {
      NOACTIONLINKTYPE: 0,
      INTERNAL: 1,
      EXTERNAL: 2
    },

    GuildMemberLevel : {
      NOGUILDMEMBERLEVEL: 0,
      GUILDPENDING: 1,
      GUILDMEMBER: 2,
      GUILDOFFICER: 3,
      GUILDLEADER: 4
    },

    GuildRaidType : {
      NOGUILDRAIDTYPE: 0,
      RAIDTYPEPERMANENT: 1,
      RAIDTYPETIMELIMITED: 2
    },

    GuildRaidRosterRefreshType : {
      NOGUILDRAIDROSTERREFRESHTYPE: 0,
      RAIDROSTERREFRESHNONE: 1,
      RAIDROSTERREFRESHSCHEDULED: 2,
      RAIDROSTERREFRESHPURCHASABLE: 3,
      RAIDROSTERREFRESHTIMED: 4
    },

    RaidState : {
      NORAIDSTATE: 0,
      RAIDINPROGRESS: 1,
      RAIDINTALLY: 2,
      RAIDCOMPLETE: 3,
      RAIDEXPIRED: 4
    },

    TerritoryRewardType : {
      NOTERRITORYREWARDTYPE: 0,
      GALACTICSCORE: 1,
      VICTORYPOINT: 2
    },

    TerritoryZoneState : {
      NOTERRITORYZONESTATE: 0,
      ZONELOCKED: 1,
      ZONEACTIVE: 2,
      ZONEOPEN: 3,
      ZONECOMPLETED: 4
    },

    TerritoryRewardStructure : {
      NOTERRITORYREWARDSTRUCTURE: 0,
      TERRITORYREWARDPERSONAL: 1,
      TERRITORYREWARDCUMULATIVE: 2
    },

    TerritoryMapPhase : {
      NOTERRITORYMAPPHASE: 0,
      TERRITORYMAPOPTIN: 1,
      TERRITORYMAPMATCHMAKING: 2,
      TERRITORYMAPSETINITIALDEFENSE: 3,
      TERRITORYMAPATTACK: 4,
      TERRITORYMAPREVIEW: 5,
      TERRITORYMAPEXPIRED: 6
    },

    StatModSlot : {
      NOSTATMODSLOT: 0,
      STATMODSLOT01: 2,
      STATMODSLOT02: 3,
      STATMODSLOT03: 4,
      STATMODSLOT04: 5,
      STATMODSLOT05: 6,
      STATMODSLOT06: 7
    },

    StatModTier : {
      NOSTATMODTIER: 0,
      STATMODTIER01: 1,
      STATMODTIER02: 2,
      STATMODTIER03: 3,
      STATMODTIER04: 4,
      STATMODTIER05: 5
    },

    StatModUpdaterType : {
      NOSTATMODUPDATERTYPE: 0,
      UPDATETYPESTATTABLE: 1,
      UPDATETYPESTATROLL: 2
    },

    ChannelEventDataType : {
      NOCHANNELEVENTDATATYPE: 0,
      MESSAGEPARAM: 1,
      TERRITORYCONFLICTACTIVITY: 3,
      TERRITORYSTRIKEACTIVITY: 4,
      TERRITORYRECONACTIVITY: 5,
      TERRITORYMAPACTIVITY: 6,
      TERRITORYCOVERTACTIVITY: 7,
      TERRITORYWARCONFLICTACTIVITY: 8,
      CHATSOCIALSTATUS: 9
    },

    TerritoryZoneInstance : {
      NOTERRITORYZONEINSTANCE: 0,
      ZONEINSTANCEBATTLE: 1,
      ZONEINSTANCEHOME: 2,
      ZONEINSTANCEAWAY: 3
    },

    ParamFormatType : {
      FORMATNONE: 0,
      FORMATSTANDARDTRUNCATE: 1,
      FORMATCOMMANODECIMAL: 2
    },

    EnrollmentStatus : {
      NOENROLLMENTSTATUS: 0,
      ENROLLMENTOPEN: 1,
      ENROLLMENTINVITE: 2,
      ENROLLMENTCLOSED: 3
    },

    GuildInviteType : {
      NOGUILDINVITETYPE: 0,
      GUILDJOINREQUEST: 1,
      GUILDINVITATION: 2
    },

    MemberContributionType : {
      NOMEMBERCONTRIBUTIONTYPE: 0,
      CONTRIBUTIONTYPECOMMENDATION: 1,
      CONTRIBUTIONTYPETRIBUTE: 2,
      CONTRIBUTIONTYPEDONATION: 3
    },

    GuildChallengeRewardType : {
      NOGUILDCHALLENGEREWARDTYPE: 0,
      GUILDCHALLENGEREWARDRANKED: 1,
      GUILDCHALLENGEREWARDCOUNT: 2
    },

    GuildChallengeTierStatus : {
      NOGUILDCHALLENGETIERSTATUS: 0,
      GUILDCHALLENGETIERLOCKED: 1,
      GUILDCHALLENGETIERACTIVE: 2,
      GUILDCHALLENGETIERCOMPLETED: 3
    },

    GuildJoinType : {
      NOGUILDJOINTYPE: 0,
      RECOMMENDED: 1,
      ALLY: 2
    },

    GuildFilterType : {
      NOGUILDFILTERTYPE: 0,
      ALLYGUILDS: 2,
      RECOMMENDEDGUILDS: 3,
      SEARCHGUILDSBYNAME: 4,
      SEARCHGUILDSBYCRITERIA: 5
    },

    GuildLeaderboardType : {
      NOGUILDLEADERBOARDTYPE: 0,
      GUILDRAIDALLCOMPPTS: 1,
      GUILDRAIDCOMPPTS: 2,
      GUILDGALACTICPOWER: 3,
      GUILDTERRITORYBATTLESTARS: 4,
      GUILDTERRITORYWAROPPONENTGALACTICPOWER: 5
    },

    PlayerProfileTab : {
      NOPLAYERPROFILETAB: 0,
      PROFILEPVPCHARACTER: 1,
      PROFILEPVPSHIP: 2,
      PROFILEPVPTOURNAMENT: 3
    },

    InboxAction : {
      ACCEPT: 0,
      REJECT: 1
    },

    EnergyRewardInstanceType : {
      NOENERGYREWARDINSTANCETYPE: 0,
      HOUROFDAY: 1
    },

    AcceptEncoding : {
      DEFAULTACCEPTENCODING: 0,
      GZIPACCEPTENCODING: 1
    },

    ResponseCode : {
      NORESPONSECODE: 0,
      OK: 1,
      ERROR: 2,
      SERVERERROR: 3,
      SESSIONEXPIRED: 4,
      AUTHFAILED: 5,
      RATEEXCEEDED: 6,
      SERVERUNAVAILABLE: 7,
      INVALIDREQUEST: 8,
      INVALIDDATA: 9,
      LEADERBOARDMATCHMAKINGERROR: 10,
      UNAUTHORIZED: 11,
      SUSPENDED: 12,
      SERVEROUTAGE: 13,
      FEATURESUSPENDED: 14,
      NETWORKUNAVAILABLE: 20,
      SEQUENCEHIGH: 30,
      SEQUENCELOW: 31,
      RECORDNOTFOUND: 32,
      EVENTNOTFOUND: 33,
      INSUFFICIENTRESOURCES: 40,
      INVALIDCLIENTVERSION: 50,
      FORCECLIENTRESTART: 51,
      INCOMPATIBLEDEVICE: 52,
      ACCOUNTUPDATED: 53,
      INVALIDRECEIPT: 60,
      PAYMENTPENDING: 61,
      OPPONENTINBATTLE: 71,
      UNDERATTACK: 72,
      OPPONENTDATASTALE: 73,
      BATTLETIMEDOUT: 74,
      PLAYERRANKSTALE: 75
    },

    ContentEncoding : {
      DEFAULTCONTENTENCODING: 0,
      GZIPCONTENTENCODING: 1
    },

    SpecialValue : {
      NOSPECIALVALUE: 0,
      NONE: 1,
      MOSTPOPULAR: 2,
      BESTVALUE: 3
    },

    StoreTab : {
      NOSTORETAB: 0,
      PACK: 1,
      PREMIUMCURRENCY: 2,
      UPSIGHT: 5,
      POWERUPBUNDLES: 10,
      SHIPPACK: 11,
      STORETAB2: 12
    },

    StoreItemType : {
      NOSTOREITEMTYPE: 0,
      STOREITEMTYPEPACK: 1,
      STOREITEMTYPEPREMIUMCURRENCY: 2,
      STOREITEMTYPEUPSIGHT: 3,
      STOREITEMTYPEPOWERUPBUNDLES: 4
    },

    StorePlatform : {
      NOSTOREPLATFORM: 0,
      APPLE: 1,
      GOOGLE: 2,
      DEV: 3,
      FB: 4
    },

    ShipmentType : {
      NOSHIPMENTTYPE: 0,
      SHIPMENTPVP: 1,
      SHIPMENTPVE: 2,
      SHIPMENTSHIPWAR: 3,
      SHIPMENTCANTINA: 4,
      SHIPMENTSHIPPVP: 5,
      SHIPMENTSHARD: 6,
      SHIPMENTGUILD: 7,
      SHIPMENTMOD: 8,
      SHIPMENTTERRITORY: 9
    },

    ShipmentRefreshType : {
      NOSHIPMENTREFRESHTYPE: 0,
      LOCAL: 1,
      GLOBAL: 2
    },

    SubscriptionType : {
      NOSUBSCRIPTIONTYPE: 0,
      SUBSCRIPTIONDAILY: 1
    },

    ChatInteraction : {
      NOCHATINTERACTION: 0,
      OPEN: 1,
      CLOSE: 2
    },

    TerritoryWarSquadStatus : {
      NOTERRITORYWARSQUADSTATUS: 0,
      SQUADAVAILABLE: 1,
      SQUADLOCKED: 2,
      SQUADDEFEATED: 3
    },

    TerritoryZoneCommandState : {
      NOTERRITORYZONECOMMANDSTATE: 0,
      NOCOMMAND: 1,
      FOCUSED: 2,
      IGNORED: 3
    },

    SquadUnitType : {
      NOSQUADUNITTYPE: 0,
      UNITTYPEDEFAULT: 1,
      UNITTYPELEADER: 2,
      UNITTYPECOMMANDER: 3,
      UNITTYPESUPPORT: 4,
      UNITTYPEREINFORCEMENT: 5
    },

    BattleTargetingTactic : {
      NOBATTLETARGETINGTACTIC: 0,
      TARGETRANDOM: 1,
      TARGETRANDOMSWITCH: 2,
      TARGETRANDOMOVERKILL: 3,
      TARGETRANDOMWEIGHTEDSWITCH: 4
    },

    TrainUnitSuccessTier : {
      TIERONESUCCESS: 0,
      TIERTWOSUCCESS: 1,
      TIERTHREESUCCESS: 2
    }

}
